INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (1,'PENDING',NULL,1,NULL,'Pending');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (2,'ACCEPT',NULL,1,NULL,'Accept');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (3,'HOLD',NULL,1,NULL,'Hold');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (4,'DECLINE',NULL,1,NULL,'Decline');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (5,'APPROVED',NULL,1,NULL,'Approved');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (6,'PUBLISHED',NULL,1,NULL,'Published');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (7,'CANCELED',NULL,1,NULL,'Canceled');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (10,'SUGGESTION',NULL,1,NULL,'Suggestion');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (11,'DISBURSED',NULL,1,NULL,'Disbursed');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (12,'TODISBURSED',NULL,1,NULL,'ToDisbursed');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (13,'PARTIALLY_DISBURSED',NULL,1,NULL,'PartiallyDisbursed');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (14,'DISBURSED_AMOUNT_EXCEED',NULL,1,NULL,'DisbursedAmountExceed');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (15,'ALREADY_SANCTION_BY_OTHER_BANK',NULL,1,NULL,'AlreadySanctionByOtherBank');

INSERT INTO proposal_status_master (ID,CODE,CREATED_BY,IS_ACTIVE,MODIFIED_BY,STATUS) VALUES (16,'ALREADY_DISBURSED_BY_OTHER_BANK',NULL,1,NULL,'AlreadyDisbursedByOtherBank');

